api_europepmc_params:
  rest_articles:
    root_url: https://www.ebi.ac.uk/europepmc/webservices/rest/
  oai_service:
    root_url: http://europepmc.org/oai.cgi 
  annotations_api:
    root_url: http://www.ebi.ac.uk/europepmc/annotations_api/annotationsByArticleIds
  archive_api:
    root_url: https://europepmc.org/ftp/oa/pmcid.txt.gz
  archive_file: ./data/pmcid.txt.gz
  article_query_folder: ./data/query_articles/
  article_human_folder: /gpfs/projects/bsc08/shared_projects/BioHackathon2022/articles_human/
  article_archive_folder: /gpfs/projects/bsc08/shared_projects/BioHackathon2022/articles_human/
  pmcid_archive_location: ./data/pmcid_archive.txt
  pmcid_human_location: ./data/pmcid_humans.txt
  pmcid_species_location: ./data/pmcid_species.txt
  pmcid_human_downloaded_location: ./data/pmcid_humans_downloaded.txt


search_params:
  ids_query_location: /gpfs/projects/bsc08/shared_projects/BioHackathon2022/articles_human/
  ids_archive_location: /gpfs/projects/bsc08/shared_projects/BioHackathon2022/articles_human/
  dl_archive: true
  rerun_archive: false
  query:  eLIfe AND (HAS_FT:Y AND OPEN_ACCESS:Y )

processing_params:
  sentence_location: ./data/candidate_sentences.csv
  json_human_folder: ./data/json_humans/
  token_sentences: [man, woman, male, female, men, women, males, females, sample]
  list_article_location: ./data/list_article.csv
  list_level_location: ./data/list_levels.csv
  list_tag_location: ./data/list_tags.csv
  list_attr_val_location: ./data/list_attr_val.csv
  list_sections_location: ./data/list_sections_details.csv
  list_parent_location: ./data/list_parent_details.csv
