api_europepmc_params:
  root_url:

  rest_articles:
    root_url: https://www.ebi.ac.uk/europepmc/webservices/rest/
  oai_service:
    root_url: http://europepmc.org/oai.cgi 
  annotations_api:
    root_url: https://www.ebi.ac.uk/europepmc/annotations_api/ 
  archive_api:
    root_url: https://europepmc.org/ftp/oa/pmcid.txt.gz
  archive_file: ./data/pmcid.txt.gz
  rerun_archive: false


sql_params:
  db_file: ./data/db.sql


ids_file_location: ./data/europepmc_id.txt

query:  HAS_FT:Y AND OPEN_ACCESS:Y AND TITLE:aspirin 