api_europepmc_params:
  rest_articles:
    root_url: https://www.ebi.ac.uk/europepmc/webservices/rest/
  oai_service:
    root_url: http://europepmc.org/oai.cgi 
  annotations_api:
    root_url: http://www.ebi.ac.uk/europepmc/annotations_api/annotationsByArticleIds
  archive_api:
    root_url: https://europepmc.org/ftp/oa/pmcid.txt.gz
  archive_file: ./data/pmcid.txt.gz
  article_query_folder: ./data/query_articles/
  article_human_folder: ./data/articles_human/
  article_archive_folder: ./data/archive_articles/
  pmcid_archive_location: ./data/pmcid_archive.txt
  pmcid_human_location: ./data/pmcid_humans.txt
  pmcid_species_location: ./data/pmcid_species.txt
  pmcid_human_downloaded_location: ./data/pmcid_humans_downloaded.txt


search_params:
  accepted_species: [human, Homo Sapiens]
  dl_archive: true
  rerun_archive: false
  query:  eLIfe AND (HAS_FT:Y AND OPEN_ACCESS:Y )

processing_params:
  candidate_sentence_location: ./data/candidate_sentences.csv

