api_europepmc_params:
  rest_articles:
    root_url: https://www.ebi.ac.uk/europepmc/webservices/rest/
  oai_service:
    root_url: http://europepmc.org/oai.cgi 
  annotations_api:
    root_url: http://www.ebi.ac.uk/europepmc/annotations_api/annotationsByArticleIds
  archive_api:
    root_url: https://europepmc.org/ftp/oa/pmcid.txt.gz
  archive_file: ./data/pmcid.txt.gz
  article_query_folder: ./data/query_articles/
  article_archive_folder: ./data/archive_articles/


search_params:
  ids_query_location: ./data/europepmc_id.txt
  ids_archive_location: ./data/archives_ids.txt
  accepted_species: [human, Homo Sapies]
  dl_archive: true
  rerun_archive: false
  query:  eLIfe AND (HAS_FT:Y AND OPEN_ACCESS:Y )
